# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: /dev/lulf
description: > # this means to ignore newlines until "baseurl:"
  Writes a post now and then when I feel I have something useful to share.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lulf.no" # the base hostname & protocol for your site
paginate: 5

author: Ulf Lilleengen
twitter_username: lulf
github_username:  lulf
plugins: [jekyll-paginate, jekyll-feed, jekyll-remote-theme]
remote_theme: samarsault/plainwhite-jekyll

# Build settings
markdown: kramdown
show_excerpts: true
#theme: plainwhite

plainwhite:
  name: Ulf Lilleengen
  portfolio_image:  "assets/me.png"
  tagline: Developer. Engineer
  disqus_shortname: lulf
  date_format: "%b %-d, %Y"
  sitemap: true
  navigation:
    - title: Blog
      url: "/"
    - title: About
      url: "/about"
  dark_mode: true
  html_lang: "en"

  social_links:
    twitter: lulf
    github: lulf
    linkedIn: in/lulf
